#!/usr/bin/python

import cmd
import sys
import dbus
import os
from phony.examples.cranky.config import Config

class CrankyShell(cmd.Cmd):
  SOCKET_FILE = Config.socket_file

  PHONY_OBJECT_PATH = Config.dbus_object_path
  PHONY_SERVICE_NAME = Config.dbus_service_name

  intro = 'Welcome to cranky shell.  Type help or ? for list of commands.\n'
  prompt = '(phony) '
  bus = None
  phony = None

  _session_bus_path = None

  def __init__(self):
    cmd.Cmd.__init__(self)

    self.find_socket_file()

    bus_path = self.session_bus_path()

    if bus_path:
      self.bus = dbus.SessionBus(bus_path)
    else:
      self.bus = dbus.SessionBus()

    try:
      self.phony = self.bus.get_object(self.PHONY_SERVICE_NAME, self.PHONY_OBJECT_PATH)
    except Exception, ex:
      raise Exception('Could not get %s: %s' % (self.PHONY_SERVICE_NAME, ex))

  def find_socket_file(self):
    socket_file = open(self.SOCKET_FILE, 'r')
    self._session_bus_path = socket_file.read()

  def session_bus_path(self):
    if self._session_bus_path:
      os.environ['DBUS_SESSION_BUS_ADDRESS'] = self._session_bus_path
      return self._session_bus_path
    else:
      return os.environ.get('DBUS_SESSION_BUS_ADDRESS')

  def do_voice(self, arg):
    try:
      self.phony.BeginVoiceDial()
    except Exception, ex:
      print str(ex)

  def do_dial(self, arg):
    try:
      self.phony.Dial(arg)
    except Exception, ex:
      print str(ex)

  def do_answer(self, arg):
    try:
      self.phony.Answer()
    except Exception, ex:
      print str(ex)

  def do_hangup(self, arg):
    try:
      self.phony.HangUp()
    except Exception, ex:
      print str(ex)

  def do_mute(self, arg):
    try:
      self.phony.Mute()
    except Exception, ex:
      print str(ex)

  def do_unmute(self, arg):
    try:
      self.phony.Unmute()
    except Exception, ex:
      print str(ex)

  def do_mic_volume(self, arg):
    try:
      self.phony.SetMicrophoneVolume(int(arg))
    except Exception, ex:
      print str(ex)

  def do_speaker_volume(self, arg):
    try:
      self.phony.SetSpeakerVolume(int(arg))
    except Exception, ex:
      print str(ex)

  def do_reset(self, arg):
    try:
      self.phony.Reset()
    except Exception, ex:
      print str(ex)

  def do_status(self, arg):
    try:
      status = self.phony.GetStatus()
      for key,val in status.iteritems():
        print '%s:\t\t%s' % (key, val)
    except Exception, ex:
      print str(ex)

  def do_state(self, arg):
    try:
      state = self.phony.GetState()
      print state
    except Exception, ex:
        print str(ex)

  def do_start_ringing(self, arg):
    try:
      self.phony.StartRinging()
    except Exception, ex:
      print str(ex)

  def do_stop_ringing(self, arg):
    try:
      self.phony.StopRinging()
    except Exception, ex:
      print str(ex)

  def do_short_ring(self, arg):
    try:
      self.phony.ShortRing()
    except Exception, ex:
      print str(ex)

  def do_simulate_off_hook(self, arg):
    try:
        self.phony.SimulateOffHook()
    except Exception, ex:
      print str(ex)

  def do_simulate_on_hook(self, arg):
    try:
        self.phony.SimulateOnHook()
    except Exception, ex:
      print str(ex)

  def do_simulate_hand_crank_turned(self, arg):
    try:
        self.phony.SimulateHandCrankTurned()
    except Exception, ex:
      print str(ex)

  def do_exit(self, arg):
    sys.exit()

  def do_quit(self, arg):
    sys.exit()

if __name__ == '__main__':
  CrankyShell().cmdloop()
